#ifndef RESOURCE_LIST_H
#define RESOURCE_LIST_H

struct ResourceInfo {
    const wchar_t* eng;
    const wchar_t* kor;
    const wchar_t* tags;
};

const ResourceInfo g_resourceInfos[] = {
    { L"<모두>", L"모든 리소스", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"EC2Instance", L"EC2 인스턴스", L"#AWS #Cloud #Compute #Computing #Infrastructure #Instance #Runtime #Server #VM #Virtual #AWS #가상머신 #가상화 #서버 #실행환경 #인스턴스 #인프라 #컴퓨트 #컴퓨팅 #클라우드" },
    { L"EC2VPC", L"VPC (가상 네트워크)", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"IAMUser", L"IAM 사용자", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Security #Tag7 #Tag8 #Tag9 #AWS #권한 #보안 #액세스 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"LambdaFunction", L"Lambda 함수", L"#AWS #Cloud #Code #Compute #Function #Infrastructure #Serverless #Tag7 #Tag8 #Tag9 #AWS #서버리스 #인프라 #컴퓨트 #코드 #클라우드 #태그7 #태그8 #태그9 #함수" },
    { L"RDSInstance", L"RDS 데이터베이스", L"#AWS #Cloud #Computing #DB #Database #Infrastructure #Instance #Relational #Runtime #SQL #AWS #DB #SQL #관계형 #데이터베이스 #실행환경 #인스턴스 #인프라 #컴퓨팅 #클라우드" },
    { L"S3Bucket", L"S3 버킷", L"#AWS #Bucket #Cloud #File #Files #Infrastructure #Object #Storage #AWS #객체 #버킷 #스토리지 #인프라 #저장소 #클라우드 #파일" },
    { L"ACMCertificate", L"ACM 인증서", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ACMPCACertificateAuthority", L"ACM PCACertificateAuthority", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ACMPCACertificateAuthorityState", L"ACM PCACertificateAuthorityState", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AMGWorkspace", L"AMGWorkspace", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AMPWorkspace", L"AMPWorkspace", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"APIGatewayAPIKey", L"APIGatewayAPIKey", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"APIGatewayClientCertificate", L"APIGatewayClient 인증서", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"APIGatewayDomainName", L"APIGatewayDomainName", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"APIGatewayRestAPI", L"APIGatewayRestAPI", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"APIGatewayUsagePlan", L"APIGatewayUsagePlan", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"APIGatewayV2API", L"APIGatewayV2API", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"APIGatewayV2VpcLink", L"APIGatewayV2 VPC 링크", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"APIGatewayVpcLink", L"APIGateway VPC 링크", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWS::AppFlow::ConnectorProfile", L"AWS::AppFlow::ConnectorProfile", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWS::AppFlow::Flow", L"AWS::AppFlow::Flow", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWS::AppRunner::Service", L"AWS::AppRunner:: 서비스", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWS::ApplicationInsights::Application", L"AWS::ApplicationInsights:: 애플리케이션", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWS::Backup::Framework", L"AWS::Backup::Framework", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWS::ECR::PublicRepository", L"AWS::ECR::Public 저장소", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWS::ECR::PullThroughCacheRule", L"AWS::ECR::PullThroughCacheRule", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWS::ECR::RegistryPolicy", L"AWS::ECR::Registry 정책", L"#AWS #Cloud #Infrastructure #Permission #Policy #Rule #Tag6 #Tag7 #Tag8 #Tag9 #AWS #권한 #규칙 #인프라 #정책 #클라우드 #태그6 #태그7 #태그8 #태그9" },
    { L"AWS::ECR::ReplicationConfiguration", L"AWS::ECR::ReplicationConfiguration", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWS::MWAA::Environment", L"AWS::MWAA:: 환경", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWS::NetworkFirewall::Firewall", L"AWS::NetworkFirewall::Firewall", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWS::NetworkFirewall::FirewallPolicy", L"AWS::NetworkFirewall::Firewall 정책", L"#AWS #Cloud #Infrastructure #Permission #Policy #Rule #Tag6 #Tag7 #Tag8 #Tag9 #AWS #권한 #규칙 #인프라 #정책 #클라우드 #태그6 #태그7 #태그8 #태그9" },
    { L"AWS::NetworkFirewall::RuleGroup", L"AWS::NetworkFirewall::Rule 그룹", L"#AWS #Cloud #Cluster #Group #Infrastructure #Logical #Tag6 #Tag7 #Tag8 #Tag9 #AWS #그룹 #논리 #인프라 #클라우드 #클러스터 #태그6 #태그7 #태그8 #태그9" },
    { L"AWS::Synthetics::Canary", L"AWS::Synthetics::Canary", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWS::Timestream::Database", L"AWS::Timestream:: 데이터베이스", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWS::Timestream::ScheduledQuery", L"AWS::Timestream::ScheduledQuery", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWS::Timestream::Table", L"AWS::Timestream:: 테이블", L"#AWS #Cloud #Data #Infrastructure #Record #Table #Tag6 #Tag7 #Tag8 #Tag9 #AWS #데이터 #레코드 #인프라 #클라우드 #태그6 #태그7 #태그8 #태그9 #테이블" },
    { L"AWS::Transfer::Workflow", L"AWS::Transfer::Workflow", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWSBackupPlan", L"AWSBackupPlan", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWSBackupRecoveryPoint", L"AWSBackupRecoveryPoint", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWSBackupSelection", L"AWSBackupSelection", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWSBackupVault", L"AWSBackupVault", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AWSBackupVaultAccessPolicy", L"AWSBackupVaultAccess 정책", L"#AWS #Cloud #Infrastructure #Permission #Policy #Rule #Tag6 #Tag7 #Tag8 #Tag9 #AWS #권한 #규칙 #인프라 #정책 #클라우드 #태그6 #태그7 #태그8 #태그9" },
    { L"AccessAnalyzer", L"AccessAnalyzer", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AppMeshGatewayRoute", L"AppMeshGatewayRoute", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AppMeshMesh", L"AppMeshMesh", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AppMeshRoute", L"AppMeshRoute", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AppMeshVirtualGateway", L"AppMeshVirtual 게이트웨이", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AppMeshVirtualNode", L"AppMeshVirtualNode", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AppMeshVirtualRouter", L"AppMeshVirtualRouter", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AppMeshVirtualService", L"AppMeshVirtual 서비스", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AppStreamDirectoryConfig", L"AppStreamDirectory 설정", L"#AWS #Application #Cloud #Desktop #Infrastructure #Streaming #Tag7 #Tag8 #Tag9 #VDA #AWS #가상화 #데스크탑 #스트리밍 #애플리케이션 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"AppStreamFleet", L"AppStreamFleet", L"#AWS #Application #Cloud #Desktop #Infrastructure #Streaming #Tag7 #Tag8 #Tag9 #VDA #AWS #가상화 #데스크탑 #스트리밍 #애플리케이션 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"AppStreamFleetState", L"AppStreamFleetState", L"#AWS #Application #Cloud #Desktop #Infrastructure #Streaming #Tag7 #Tag8 #Tag9 #VDA #AWS #가상화 #데스크탑 #스트리밍 #애플리케이션 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"AppStreamImage", L"AppStream 이미지", L"#AWS #Application #Cloud #Desktop #Infrastructure #Streaming #Tag7 #Tag8 #Tag9 #VDA #AWS #가상화 #데스크탑 #스트리밍 #애플리케이션 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"AppStreamImageBuilder", L"AppStreamImageBuilder", L"#AWS #Application #Cloud #Desktop #Infrastructure #Streaming #Tag7 #Tag8 #Tag9 #VDA #AWS #가상화 #데스크탑 #스트리밍 #애플리케이션 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"AppStreamImageBuilderWaiter", L"AppStreamImageBuilderWaiter", L"#AWS #Application #Cloud #Desktop #Infrastructure #Streaming #Tag7 #Tag8 #Tag9 #VDA #AWS #가상화 #데스크탑 #스트리밍 #애플리케이션 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"AppStreamStack", L"AppStream 스택", L"#AWS #Application #Cloud #Desktop #Infrastructure #Streaming #Tag7 #Tag8 #Tag9 #VDA #AWS #가상화 #데스크탑 #스트리밍 #애플리케이션 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"AppStreamStackFleetAttachment", L"AppStreamStackFleetAttachment", L"#AWS #Application #Cloud #Desktop #Infrastructure #Streaming #Tag7 #Tag8 #Tag9 #VDA #AWS #가상화 #데스크탑 #스트리밍 #애플리케이션 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"AppSyncGraphqlAPI", L"AppSyncGraphqlAPI", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ApplicationAutoScalingScalableTarget", L"ApplicationAutoScalingScalableTarget", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ArchiveRule", L"ArchiveRule", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AthenaNamedQuery", L"AthenaNamedQuery", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"AthenaWorkGroup", L"AthenaWork 그룹", L"#AWS #Cloud #Cluster #Group #Infrastructure #Logical #Tag6 #Tag7 #Tag8 #Tag9 #AWS #그룹 #논리 #인프라 #클라우드 #클러스터 #태그6 #태그7 #태그8 #태그9" },
    { L"AutoScalingGroup", L"AutoScaling 그룹", L"#AWS #Cloud #Cluster #Group #Infrastructure #Logical #Tag6 #Tag7 #Tag8 #Tag9 #AWS #그룹 #논리 #인프라 #클라우드 #클러스터 #태그6 #태그7 #태그8 #태그9" },
    { L"AutoScalingPlansScalingPlan", L"AutoScalingPlansScalingPlan", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"BatchComputeEnvironment", L"BatchCompute 환경", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"BatchComputeEnvironmentState", L"BatchComputeEnvironmentState", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"BatchJobQueue", L"BatchJob 큐(대기열)", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"BatchJobQueueState", L"BatchJobQueueState", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"BillingCostandUsageReport", L"BillingCostandUsageReport", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"Budget", L"Budget", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"Cloud9Environment", L"Cloud9 환경", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CloudDirectoryDirectory", L"CloudDirectoryDirectory", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CloudDirectorySchema", L"CloudDirectorySchema", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CloudFormationStack", L"CloudFormation 스택", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CloudFormationStackSet", L"CloudFormationStackSet", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CloudFormationType", L"CloudFormationType", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CloudFrontDistribution", L"CloudFront 배포(CDN)", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CloudFrontDistributionDeployment", L"CloudFrontDistributionDeployment", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CloudFrontOriginAccessIdentity", L"CloudFrontOriginAccessIdentity", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CloudHSMV2Cluster", L"CloudHSMV2 클러스터", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CloudHSMV2ClusterHSM", L"CloudHSMV2ClusterHSM", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CloudSearchDomain", L"CloudSearch 도메인", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CloudTrailTrail", L"CloudTrailTrail", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CloudWatchAlarm", L"CloudWatch 알람", L"#AWS #Alert #Cloud #Infrastructure #Logging #Metrics #Monitoring #Tag7 #Tag8 #Tag9 #AWS #로그 #메트릭 #모니터링 #알람 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"CloudWatchDashboard", L"CloudWatch Dashboard", L"#AWS #Alert #Cloud #Infrastructure #Logging #Metrics #Monitoring #Tag7 #Tag8 #Tag9 #AWS #로그 #메트릭 #모니터링 #알람 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"CloudWatchEventsBuses", L"CloudWatch EventsBuses", L"#AWS #Alert #Cloud #Infrastructure #Logging #Metrics #Monitoring #Tag7 #Tag8 #Tag9 #AWS #로그 #메트릭 #모니터링 #알람 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"CloudWatchEventsRule", L"CloudWatch EventsRule", L"#AWS #Alert #Cloud #Infrastructure #Logging #Metrics #Monitoring #Tag7 #Tag8 #Tag9 #AWS #로그 #메트릭 #모니터링 #알람 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"CloudWatchEventsTarget", L"CloudWatch EventsTarget", L"#AWS #Alert #Cloud #Infrastructure #Logging #Metrics #Monitoring #Tag7 #Tag8 #Tag9 #AWS #로그 #메트릭 #모니터링 #알람 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"CloudWatchLogsDestination", L"CloudWatch LogsDestination", L"#AWS #Alert #Cloud #Infrastructure #Logging #Metrics #Monitoring #Tag7 #Tag8 #Tag9 #AWS #로그 #메트릭 #모니터링 #알람 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"CloudWatchLogsLogGroup", L"CloudWatch 로그 그룹", L"#AWS #Alert #Cloud #Cluster #Group #Infrastructure #Logging #Logical #Metrics #Monitoring #AWS #그룹 #논리 #로그 #메트릭 #모니터링 #알람 #인프라 #클라우드 #클러스터" },
    { L"CloudWatchLogsResourcePolicy", L"CloudWatch LogsResource 정책", L"#AWS #Alert #Cloud #Infrastructure #Logging #Metrics #Monitoring #Permission #Policy #Rule #AWS #권한 #규칙 #로그 #메트릭 #모니터링 #알람 #인프라 #정책 #클라우드" },
    { L"CodeArtifactDomain", L"CodeArtifact 도메인", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CodeArtifactRepository", L"CodeArtifact 저장소", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CodeBuildProject", L"CodeBuild 프로젝트", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CodeCommitRepository", L"CodeCommit 저장소", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CodeDeployApplication", L"CodeDeploy 애플리케이션", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CodePipelinePipeline", L"CodePipeline 파이프라인", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CodeStarConnection", L"CodeStar 연결", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CodeStarNotificationRule", L"CodeStarNotificationRule", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CodeStarProject", L"CodeStar 프로젝트", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"CognitoIdentityPool", L"CognitoIdentityPool", L"#AWS #Auth #Cloud #Identity #Infrastructure #Tag7 #Tag8 #Tag9 #User #Web #AWS #고객 #사용자 #웹 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"CognitoIdentityProvider", L"CognitoIdentityProvider", L"#AWS #Auth #Cloud #Identity #Infrastructure #Tag7 #Tag8 #Tag9 #User #Web #AWS #고객 #사용자 #웹 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"CognitoUserPool", L"CognitoUserPool", L"#AWS #Auth #Cloud #Identity #Infrastructure #Tag7 #Tag8 #Tag9 #User #Web #AWS #고객 #사용자 #웹 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"CognitoUserPoolClient", L"CognitoUserPoolClient", L"#AWS #Auth #Cloud #Identity #Infrastructure #Tag7 #Tag8 #Tag9 #User #Web #AWS #고객 #사용자 #웹 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"CognitoUserPoolDomain", L"CognitoUserPool 도메인", L"#AWS #Auth #Cloud #Identity #Infrastructure #Tag7 #Tag8 #Tag9 #User #Web #AWS #고객 #사용자 #웹 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"ComprehendDocumentClassifier", L"ComprehendDocumentClassifier", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ComprehendDominantLanguageDetectionJob", L"ComprehendDominantLanguageDetectionJob", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ComprehendEndpoint", L"ComprehendEndpoint", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ComprehendEntitiesDetectionJob", L"ComprehendEntitiesDetectionJob", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ComprehendEntityRecognizer", L"ComprehendEntityRecognizer", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ComprehendKeyPhrasesDetectionJob", L"ComprehendKeyPhrasesDetectionJob", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ComprehendSentimentDetectionJob", L"ComprehendSentimentDetectionJob", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ConfigServiceConfigRule", L"ConfigServiceConfigRule", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ConfigServiceConfigurationRecorder", L"ConfigServiceConfigurationRecorder", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ConfigServiceDeliveryChannel", L"ConfigServiceDeliveryChannel", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"DAXCluster", L"DAX 클러스터", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"DAXParameterGroup", L"DAXParameter 그룹", L"#AWS #Cloud #Cluster #Group #Infrastructure #Logical #Tag6 #Tag7 #Tag8 #Tag9 #AWS #그룹 #논리 #인프라 #클라우드 #클러스터 #태그6 #태그7 #태그8 #태그9" },
    { L"DAXSubnetGroup", L"DAXSubnet 그룹", L"#AWS #Cloud #Cluster #Group #Infrastructure #Logical #Tag6 #Tag7 #Tag8 #Tag9 #AWS #그룹 #논리 #인프라 #클라우드 #클러스터 #태그6 #태그7 #태그8 #태그9" },
    { L"DataPipelinePipeline", L"DataPipeline 파이프라인", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"DatabaseMigrationServiceCertificate", L"DatabaseMigrationService 인증서", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"DatabaseMigrationServiceEndpoint", L"DatabaseMigrationServiceEndpoint", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"DatabaseMigrationServiceEventSubscription", L"DatabaseMigrationServiceEventSubscription", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"DatabaseMigrationServiceReplicationInstance", L"DatabaseMigrationServiceReplication 인스턴스", L"#AWS #Cloud #Computing #Infrastructure #Instance #Runtime #Tag6 #Tag7 #Tag8 #Tag9 #AWS #실행환경 #인스턴스 #인프라 #컴퓨팅 #클라우드 #태그6 #태그7 #태그8 #태그9" },
    { L"DatabaseMigrationServiceReplicationTask", L"DatabaseMigrationServiceReplicationTask", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"DatabaseMigrationServiceSubnetGroup", L"DatabaseMigrationServiceSubnet 그룹", L"#AWS #Cloud #Cluster #Group #Infrastructure #Logical #Tag6 #Tag7 #Tag8 #Tag9 #AWS #그룹 #논리 #인프라 #클라우드 #클러스터 #태그6 #태그7 #태그8 #태그9" },
    { L"DeviceFarmProject", L"DeviceFarm 프로젝트", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"DirectoryServiceDirectory", L"DirectoryServiceDirectory", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"DynamoDBTable", L"DynamoDB 테이블", L"#AWS #Cloud #Data #Database #Infrastructure #KV #NoSQL #Record #Serverless #Table #AWS #NoSQL #데이터 #데이터베이스 #레코드 #서버리스 #인프라 #클라우드 #키벨류 #테이블" },
    { L"DynamoDBTableItem", L"DynamoDBTableItem", L"#AWS #Cloud #Database #Infrastructure #KV #NoSQL #Serverless #Tag7 #Tag8 #Tag9 #AWS #NoSQL #데이터베이스 #서버리스 #인프라 #클라우드 #키벨류 #태그7 #태그8 #태그9" },
    { L"EC2Address", L"EC2 공인 IP(EIP)", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2ClientVpnEndpoint", L"EC2 ClientVpnEndpoint", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2ClientVpnEndpointAttachment", L"EC2 ClientVpnEndpointAttachment", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2CustomerGateway", L"EC2 Customer 게이트웨이", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2DHCPOption", L"EC2 DHCPOption", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2DefaultSecurityGroupRule", L"EC2 DefaultSecurityGroupRule", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2EgressOnlyInternetGateway", L"EC2 EgressOnlyInternet 게이트웨이", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2Host", L"EC2 Host", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2Image", L"EC2 이미지", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2InternetGateway", L"인터넷 게이트웨이", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2InternetGatewayAttachment", L"EC2 InternetGatewayAttachment", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2KeyPair", L"EC2 키 페어", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2LaunchTemplate", L"EC2 LaunchTemplate", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2NATGateway", L"EC2 NAT 게이트웨이", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2NetworkACL", L"EC2 NetworkACL", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2NetworkInterface", L"EC2 네트워크 인터페이스 (ENI)", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2PlacementGroup", L"EC2 Placement 그룹", L"#AWS #Cloud #Cluster #Compute #Group #Infrastructure #Logical #Server #VM #Virtual #AWS #가상머신 #가상화 #그룹 #논리 #서버 #인프라 #컴퓨트 #클라우드 #클러스터" },
    { L"EC2RouteTable", L"라우팅 테이블", L"#AWS #Cloud #Compute #Data #Infrastructure #Record #Server #Table #VM #Virtual #AWS #가상머신 #가상화 #데이터 #레코드 #서버 #인프라 #컴퓨트 #클라우드 #테이블" },
    { L"EC2SecurityGroup", L"보안 그룹", L"#AWS #Cloud #Cluster #Compute #Group #Infrastructure #Logical #Server #VM #Virtual #AWS #가상머신 #가상화 #그룹 #논리 #서버 #인프라 #컴퓨트 #클라우드 #클러스터" },
    { L"EC2Snapshot", L"EBS 스냅샷", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2SpotFleetRequest", L"EC2 SpotFleetRequest", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2Subnet", L"VPC 서브넷", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2TGW", L"EC2 TGW", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2TGWAttachment", L"EC2 TGWAttachment", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2VPCEndpoint", L"EC2 VPCEndpoint", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2VPCEndpointConnection", L"EC2 VPCEndpoint 연결", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2VPCEndpointServiceConfiguration", L"EC2 VPCEndpointServiceConfiguration", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2VPCPeeringConnection", L"EC2 VPCPeering 연결", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2VPNConnection", L"EC2 VPN 연결", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2VPNGateway", L"EC2 VPN 게이트웨이", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2VPNGatewayAttachment", L"EC2 VPNGatewayAttachment", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"EC2Volume", L"EBS 볼륨", L"#AWS #Cloud #Compute #Infrastructure #Server #Tag7 #Tag8 #Tag9 #VM #Virtual #AWS #가상머신 #가상화 #서버 #인프라 #컴퓨트 #클라우드 #태그7 #태그8 #태그9" },
    { L"ECRRepository", L"ECR 저장소", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ECSCluster", L"ECS 클러스터", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ECSClusterInstance", L"ECS Cluster 인스턴스", L"#AWS #Cloud #Computing #Infrastructure #Instance #Runtime #Tag6 #Tag7 #Tag8 #Tag9 #AWS #실행환경 #인스턴스 #인프라 #컴퓨팅 #클라우드 #태그6 #태그7 #태그8 #태그9" },
    { L"ECSService", L"ECS 서비스", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ECSTask", L"ECS Task", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ECSTaskDefinition", L"ECS TaskDefinition", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"EFSFileSystem", L"EFSFileSystem", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"EFSMountTarget", L"EFSMountTarget", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"EKSCluster", L"EKS 클러스터", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"EKSFargateProfiles", L"EKS FargateProfiles", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"EKSNodegroups", L"EKS Nodegroups", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ELB", L"Classic 로드 밸런서", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ELBv2", L"Application/Network 로드 밸런서", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ELBv2TargetGroup", L"ELBv2Target 그룹", L"#AWS #Cloud #Cluster #Group #Infrastructure #Logical #Tag6 #Tag7 #Tag8 #Tag9 #AWS #그룹 #논리 #인프라 #클라우드 #클러스터 #태그6 #태그7 #태그8 #태그9" },
    { L"EMRCluster", L"EMR 클러스터", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"EMRSecurityConfiguration", L"EMRSecurityConfiguration", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ESDomain", L"ES 도메인", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ElasticBeanstalkApplication", L"ElasticBeanstalk 애플리케이션", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ElasticBeanstalkEnvironment", L"ElasticBeanstalk 환경", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ElasticTranscoderPipeline", L"ElasticTranscoder 파이프라인", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ElasticacheCacheCluster", L"ElasticacheCache 클러스터", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ElasticacheCacheParameterGroup", L"ElasticacheCacheParameter 그룹", L"#AWS #Cloud #Cluster #Group #Infrastructure #Logical #Tag6 #Tag7 #Tag8 #Tag9 #AWS #그룹 #논리 #인프라 #클라우드 #클러스터 #태그6 #태그7 #태그8 #태그9" },
    { L"ElasticacheReplicationGroup", L"ElasticacheReplication 그룹", L"#AWS #Cloud #Cluster #Group #Infrastructure #Logical #Tag6 #Tag7 #Tag8 #Tag9 #AWS #그룹 #논리 #인프라 #클라우드 #클러스터 #태그6 #태그7 #태그8 #태그9" },
    { L"ElasticacheSubnetGroup", L"ElasticacheSubnet 그룹", L"#AWS #Cloud #Cluster #Group #Infrastructure #Logical #Tag6 #Tag7 #Tag8 #Tag9 #AWS #그룹 #논리 #인프라 #클라우드 #클러스터 #태그6 #태그7 #태그8 #태그9" },
    { L"FMSNotificationChannel", L"FMSNotificationChannel", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"FMSPolicy", L"FMS 정책", L"#AWS #Cloud #Infrastructure #Permission #Policy #Rule #Tag6 #Tag7 #Tag8 #Tag9 #AWS #권한 #규칙 #인프라 #정책 #클라우드 #태그6 #태그7 #태그8 #태그9" },
    { L"FSxBackup", L"FSxBackup", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"FSxFileSystem", L"FSxFileSystem", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"FirehoseDeliveryStream", L"FirehoseDeliveryStream", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"GlobalAccelerator", L"GlobalAccelerator", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"GlobalAcceleratorEndpointGroup", L"GlobalAcceleratorEndpoint 그룹", L"#AWS #Cloud #Cluster #Group #Infrastructure #Logical #Tag6 #Tag7 #Tag8 #Tag9 #AWS #그룹 #논리 #인프라 #클라우드 #클러스터 #태그6 #태그7 #태그8 #태그9" },
    { L"GlobalAcceleratorListener", L"GlobalAcceleratorListener", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"GlueClassifier", L"GlueClassifier", L"#AWS #Analytics #Catalog #Cloud #Data #ETL #Infrastructure #Tag7 #Tag8 #Tag9 #AWS #ETL #데이터 #분석 #인프라 #카탈로그 #클라우드 #태그7 #태그8 #태그9" },
    { L"GlueConnection", L"Glue 연결", L"#AWS #Analytics #Catalog #Cloud #Data #ETL #Infrastructure #Tag7 #Tag8 #Tag9 #AWS #ETL #데이터 #분석 #인프라 #카탈로그 #클라우드 #태그7 #태그8 #태그9" },
    { L"GlueCrawler", L"GlueCrawler", L"#AWS #Analytics #Catalog #Cloud #Data #ETL #Infrastructure #Tag7 #Tag8 #Tag9 #AWS #ETL #데이터 #분석 #인프라 #카탈로그 #클라우드 #태그7 #태그8 #태그9" },
    { L"GlueDataBrewDatasets", L"GlueDataBrewDatasets", L"#AWS #Analytics #Catalog #Cloud #Data #ETL #Infrastructure #Tag7 #Tag8 #Tag9 #AWS #ETL #데이터 #분석 #인프라 #카탈로그 #클라우드 #태그7 #태그8 #태그9" },
    { L"GlueDataBrewJobs", L"GlueDataBrewJobs", L"#AWS #Analytics #Catalog #Cloud #Data #ETL #Infrastructure #Tag7 #Tag8 #Tag9 #AWS #ETL #데이터 #분석 #인프라 #카탈로그 #클라우드 #태그7 #태그8 #태그9" },
    { L"GlueDataBrewProjects", L"GlueDataBrewProjects", L"#AWS #Analytics #Catalog #Cloud #Data #ETL #Infrastructure #Tag7 #Tag8 #Tag9 #AWS #ETL #데이터 #분석 #인프라 #카탈로그 #클라우드 #태그7 #태그8 #태그9" },
    { L"GlueDataBrewRecipe", L"GlueDataBrewRecipe", L"#AWS #Analytics #Catalog #Cloud #Data #ETL #Infrastructure #Tag7 #Tag8 #Tag9 #AWS #ETL #데이터 #분석 #인프라 #카탈로그 #클라우드 #태그7 #태그8 #태그9" },
    { L"GlueDataBrewRulesets", L"GlueDataBrewRulesets", L"#AWS #Analytics #Catalog #Cloud #Data #ETL #Infrastructure #Tag7 #Tag8 #Tag9 #AWS #ETL #데이터 #분석 #인프라 #카탈로그 #클라우드 #태그7 #태그8 #태그9" },
    { L"GlueDataBrewSchedules", L"GlueDataBrewSchedules", L"#AWS #Analytics #Catalog #Cloud #Data #ETL #Infrastructure #Tag7 #Tag8 #Tag9 #AWS #ETL #데이터 #분석 #인프라 #카탈로그 #클라우드 #태그7 #태그8 #태그9" },
    { L"GlueDatabase", L"Glue 데이터베이스", L"#AWS #Analytics #Catalog #Cloud #Data #ETL #Infrastructure #Tag7 #Tag8 #Tag9 #AWS #ETL #데이터 #분석 #인프라 #카탈로그 #클라우드 #태그7 #태그8 #태그9" },
    { L"GlueDevEndpoint", L"GlueDevEndpoint", L"#AWS #Analytics #Catalog #Cloud #Data #ETL #Infrastructure #Tag7 #Tag8 #Tag9 #AWS #ETL #데이터 #분석 #인프라 #카탈로그 #클라우드 #태그7 #태그8 #태그9" },
    { L"GlueJob", L"GlueJob", L"#AWS #Analytics #Catalog #Cloud #Data #ETL #Infrastructure #Tag7 #Tag8 #Tag9 #AWS #ETL #데이터 #분석 #인프라 #카탈로그 #클라우드 #태그7 #태그8 #태그9" },
    { L"GlueTrigger", L"GlueTrigger", L"#AWS #Analytics #Catalog #Cloud #Data #ETL #Infrastructure #Tag7 #Tag8 #Tag9 #AWS #ETL #데이터 #분석 #인프라 #카탈로그 #클라우드 #태그7 #태그8 #태그9" },
    { L"GuardDutyDetector", L"GuardDutyDetector", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"IAMGroup", L"IAM 그룹", L"#AWS #Access #Auth #Cloud #Cluster #Group #Identity #Infrastructure #Logical #Security #AWS #권한 #그룹 #논리 #보안 #액세스 #인증 #인프라 #클라우드 #클러스터" },
    { L"IAMGroupPolicy", L"IAM Group 정책", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Permission #Policy #Rule #Security #AWS #권한 #규칙 #보안 #액세스 #인증 #인프라 #정책 #클라우드" },
    { L"IAMGroupPolicyAttachment", L"IAM GroupPolicyAttachment", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Security #Tag7 #Tag8 #Tag9 #AWS #권한 #보안 #액세스 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"IAMInstanceProfile", L"IAM InstanceProfile", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Security #Tag7 #Tag8 #Tag9 #AWS #권한 #보안 #액세스 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"IAMInstanceProfileRole", L"IAM InstanceProfile 역할", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Security #Tag7 #Tag8 #Tag9 #AWS #권한 #보안 #액세스 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"IAMLoginProfile", L"IAM LoginProfile", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Security #Tag7 #Tag8 #Tag9 #AWS #권한 #보안 #액세스 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"IAMOpenIDConnectProvider", L"IAM OpenIDConnectProvider", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Security #Tag7 #Tag8 #Tag9 #AWS #권한 #보안 #액세스 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"IAMPolicy", L"IAM 정책", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Permission #Policy #Rule #Security #AWS #권한 #규칙 #보안 #액세스 #인증 #인프라 #정책 #클라우드" },
    { L"IAMRole", L"IAM 역할", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Security #Tag7 #Tag8 #Tag9 #AWS #권한 #보안 #액세스 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"IAMRolePolicy", L"IAM Role 정책", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Permission #Policy #Rule #Security #AWS #권한 #규칙 #보안 #액세스 #인증 #인프라 #정책 #클라우드" },
    { L"IAMRolePolicyAttachment", L"IAM RolePolicyAttachment", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Security #Tag7 #Tag8 #Tag9 #AWS #권한 #보안 #액세스 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"IAMSAMLProvider", L"IAM SAMLProvider", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Security #Tag7 #Tag8 #Tag9 #AWS #권한 #보안 #액세스 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"IAMServerCertificate", L"IAM Server 인증서", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Security #Tag7 #Tag8 #Tag9 #AWS #권한 #보안 #액세스 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"IAMServiceSpecificCredential", L"IAM ServiceSpecificCredential", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Security #Tag7 #Tag8 #Tag9 #AWS #권한 #보안 #액세스 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"IAMSigningCertificate", L"IAM Signing 인증서", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Security #Tag7 #Tag8 #Tag9 #AWS #권한 #보안 #액세스 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"IAMUserAccessKey", L"IAM UserAccessKey", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Security #Tag7 #Tag8 #Tag9 #AWS #권한 #보안 #액세스 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"IAMUserGroupAttachment", L"IAM UserGroupAttachment", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Security #Tag7 #Tag8 #Tag9 #AWS #권한 #보안 #액세스 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"IAMUserPolicy", L"IAM User 정책", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Permission #Policy #Rule #Security #AWS #권한 #규칙 #보안 #액세스 #인증 #인프라 #정책 #클라우드" },
    { L"IAMUserPolicyAttachment", L"IAM UserPolicyAttachment", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Security #Tag7 #Tag8 #Tag9 #AWS #권한 #보안 #액세스 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"IAMUserSSHPublicKey", L"IAM UserSSHPublicKey", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Security #Tag7 #Tag8 #Tag9 #AWS #권한 #보안 #액세스 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"IAMVirtualMFADevice", L"IAM VirtualMFADevice", L"#AWS #Access #Auth #Cloud #Identity #Infrastructure #Security #Tag7 #Tag8 #Tag9 #AWS #권한 #보안 #액세스 #인증 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"ImageBuilderComponent", L"ImageBuilderComponent", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ImageBuilderDistributionConfiguration", L"ImageBuilderDistributionConfiguration", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ImageBuilderImage", L"ImageBuilder 이미지", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ImageBuilderInfrastructureConfiguration", L"ImageBuilderInfrastructureConfiguration", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ImageBuilderPipeline", L"ImageBuilder 파이프라인", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ImageBuilderRecipe", L"ImageBuilderRecipe", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"Inspector2", L"Inspector2", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"InspectorAssessmentRun", L"InspectorAssessmentRun", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"InspectorAssessmentTarget", L"InspectorAssessmentTarget", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"InspectorAssessmentTemplate", L"InspectorAssessmentTemplate", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"IoTAuthorizer", L"IoTAuthorizer", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"IoTCACertificate", L"IoTCA 인증서", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"IoTCertificate", L"IoT 인증서", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"IoTJob", L"IoTJob", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"IoTOTAUpdate", L"IoTOTAUpdate", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"IoTPolicy", L"IoT 정책", L"#AWS #Cloud #Infrastructure #Permission #Policy #Rule #Tag6 #Tag7 #Tag8 #Tag9 #AWS #권한 #규칙 #인프라 #정책 #클라우드 #태그6 #태그7 #태그8 #태그9" },
    { L"IoTRoleAlias", L"IoTRoleAlias", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"IoTStream", L"IoTStream", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"IoTThing", L"IoTThing", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"IoTThingGroup", L"IoTThing 그룹", L"#AWS #Cloud #Cluster #Group #Infrastructure #Logical #Tag6 #Tag7 #Tag8 #Tag9 #AWS #그룹 #논리 #인프라 #클라우드 #클러스터 #태그6 #태그7 #태그8 #태그9" },
    { L"IoTThingType", L"IoTThingType", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"IoTThingTypeState", L"IoTThingTypeState", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"IoTTopicRule", L"IoTTopicRule", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"KMSAlias", L"KMS Alias", L"#AWS #Cloud #Encryption #Infrastructure #Key #Management #Security #Tag7 #Tag8 #Tag9 #AWS #관리 #보안 #암호화 #인프라 #클라우드 #키 #태그7 #태그8 #태그9" },
    { L"KMSKey", L"KMS Key", L"#AWS #Cloud #Encryption #Infrastructure #Key #Management #Security #Tag7 #Tag8 #Tag9 #AWS #관리 #보안 #암호화 #인프라 #클라우드 #키 #태그7 #태그8 #태그9" },
    { L"KendraIndex", L"KendraIndex", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"KinesisAnalyticsApplication", L"KinesisAnalytics 애플리케이션", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"KinesisStream", L"KinesisStream", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"KinesisVideoProject", L"KinesisVideo 프로젝트", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"LambdaEventSourceMapping", L"Lambda EventSourceMapping", L"#AWS #Cloud #Code #Compute #Function #Infrastructure #Serverless #Tag7 #Tag8 #Tag9 #AWS #서버리스 #인프라 #컴퓨트 #코드 #클라우드 #태그7 #태그8 #태그9 #함수" },
    { L"LambdaLayer", L"Lambda Layer", L"#AWS #Cloud #Code #Compute #Function #Infrastructure #Serverless #Tag7 #Tag8 #Tag9 #AWS #서버리스 #인프라 #컴퓨트 #코드 #클라우드 #태그7 #태그8 #태그9 #함수" },
    { L"LaunchConfiguration", L"LaunchConfiguration", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"LexBot", L"LexBot", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"LexIntent", L"LexIntent", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"LexModelBuildingServiceBotAlias", L"LexModelBuildingServiceBotAlias", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"LexSlotType", L"LexSlotType", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"LifecycleHook", L"LifecycleHook", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"LightsailDisk", L"LightsailDisk", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"LightsailDomain", L"Lightsail 도메인", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"LightsailInstance", L"Lightsail 인스턴스", L"#AWS #Cloud #Computing #Infrastructure #Instance #Runtime #Tag6 #Tag7 #Tag8 #Tag9 #AWS #실행환경 #인스턴스 #인프라 #컴퓨팅 #클라우드 #태그6 #태그7 #태그8 #태그9" },
    { L"LightsailKeyPair", L"Lightsail 키 페어", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"LightsailLoadBalancer", L"Lightsail 로드 밸런서", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"LightsailStaticIP", L"LightsailStaticIP", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"MQBroker", L"MQBroker", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"MSKCluster", L"MSK 클러스터", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"MSKConfiguration", L"MSKConfiguration", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"MachineLearningBranchPrediction", L"MachineLearningBranchPrediction", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"MachineLearningDataSource", L"MachineLearningDataSource", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"MachineLearningEvaluation", L"MachineLearningEvaluation", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"MachineLearningMLModel", L"MachineLearningMLModel", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"Macie", L"Macie", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"MediaConvertJobTemplate", L"MediaConvertJobTemplate", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"MediaConvertPreset", L"MediaConvertPreset", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"MediaConvertQueue", L"MediaConvert 큐(대기열)", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"MediaLiveChannel", L"MediaLiveChannel", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"MediaLiveInput", L"MediaLiveInput", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"MediaLiveInputSecurityGroup", L"MediaLiveInputSecurity 그룹", L"#AWS #Cloud #Cluster #Group #Infrastructure #Logical #Tag6 #Tag7 #Tag8 #Tag9 #AWS #그룹 #논리 #인프라 #클라우드 #클러스터 #태그6 #태그7 #태그8 #태그9" },
    { L"MediaPackageChannel", L"MediaPackageChannel", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"MediaPackageOriginEndpoint", L"MediaPackageOriginEndpoint", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"MediaStoreContainer", L"MediaStoreContainer", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"MediaStoreDataItems", L"MediaStoreDataItems", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"MediaTailorConfiguration", L"MediaTailorConfiguration", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"MobileProject", L"Mobile 프로젝트", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"NeptuneCluster", L"Neptune 클러스터", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"NeptuneInstance", L"Neptune 인스턴스", L"#AWS #Cloud #Computing #Infrastructure #Instance #Runtime #Tag6 #Tag7 #Tag8 #Tag9 #AWS #실행환경 #인스턴스 #인프라 #컴퓨팅 #클라우드 #태그6 #태그7 #태그8 #태그9" },
    { L"NetpuneSnapshot", L"Netpune 스냅샷", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"OSDomain", L"OS 도메인", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"OpsWorksApp", L"OpsWorksApp", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"OpsWorksCMBackup", L"OpsWorksCMBackup", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"OpsWorksCMServer", L"OpsWorksCMServer", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"OpsWorksCMServerState", L"OpsWorksCMServerState", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"OpsWorksInstance", L"OpsWorks 인스턴스", L"#AWS #Cloud #Computing #Infrastructure #Instance #Runtime #Tag6 #Tag7 #Tag8 #Tag9 #AWS #실행환경 #인스턴스 #인프라 #컴퓨팅 #클라우드 #태그6 #태그7 #태그8 #태그9" },
    { L"OpsWorksLayer", L"OpsWorksLayer", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"OpsWorksUserProfile", L"OpsWorksUserProfile", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"QLDBLedger", L"QLDBLedger", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"RDSClusterSnapshot", L"RDS Cluster 스냅샷", L"#AWS #Cloud #DB #Database #Infrastructure #Relational #SQL #Tag7 #Tag8 #Tag9 #AWS #DB #SQL #관계형 #데이터베이스 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"RDSDBCluster", L"RDS DB 클러스터", L"#AWS #Cloud #DB #Database #Infrastructure #Relational #SQL #Tag7 #Tag8 #Tag9 #AWS #DB #SQL #관계형 #데이터베이스 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"RDSDBClusterParameterGroup", L"RDS DBClusterParameter 그룹", L"#AWS #Cloud #Cluster #DB #Database #Group #Infrastructure #Logical #Relational #SQL #AWS #DB #SQL #관계형 #그룹 #논리 #데이터베이스 #인프라 #클라우드 #클러스터" },
    { L"RDSDBParameterGroup", L"RDS DBParameter 그룹", L"#AWS #Cloud #Cluster #DB #Database #Group #Infrastructure #Logical #Relational #SQL #AWS #DB #SQL #관계형 #그룹 #논리 #데이터베이스 #인프라 #클라우드 #클러스터" },
    { L"RDSDBSubnetGroup", L"RDS DBSubnet 그룹", L"#AWS #Cloud #Cluster #DB #Database #Group #Infrastructure #Logical #Relational #SQL #AWS #DB #SQL #관계형 #그룹 #논리 #데이터베이스 #인프라 #클라우드 #클러스터" },
    { L"RDSEventSubscription", L"RDS EventSubscription", L"#AWS #Cloud #DB #Database #Infrastructure #Relational #SQL #Tag7 #Tag8 #Tag9 #AWS #DB #SQL #관계형 #데이터베이스 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"RDSOptionGroup", L"RDS Option 그룹", L"#AWS #Cloud #Cluster #DB #Database #Group #Infrastructure #Logical #Relational #SQL #AWS #DB #SQL #관계형 #그룹 #논리 #데이터베이스 #인프라 #클라우드 #클러스터" },
    { L"RDSProxy", L"RDS Proxy", L"#AWS #Cloud #DB #Database #Infrastructure #Relational #SQL #Tag7 #Tag8 #Tag9 #AWS #DB #SQL #관계형 #데이터베이스 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"RDSSnapshot", L"RDS 스냅샷", L"#AWS #Cloud #DB #Database #Infrastructure #Relational #SQL #Tag7 #Tag8 #Tag9 #AWS #DB #SQL #관계형 #데이터베이스 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"RedshiftCluster", L"Redshift 클러스터", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"RedshiftParameterGroup", L"RedshiftParameter 그룹", L"#AWS #Cloud #Cluster #Group #Infrastructure #Logical #Tag6 #Tag7 #Tag8 #Tag9 #AWS #그룹 #논리 #인프라 #클라우드 #클러스터 #태그6 #태그7 #태그8 #태그9" },
    { L"RedshiftSnapshot", L"Redshift 스냅샷", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"RedshiftSubnetGroup", L"RedshiftSubnet 그룹", L"#AWS #Cloud #Cluster #Group #Infrastructure #Logical #Tag6 #Tag7 #Tag8 #Tag9 #AWS #그룹 #논리 #인프라 #클라우드 #클러스터 #태그6 #태그7 #태그8 #태그9" },
    { L"RekognitionCollection", L"RekognitionCollection", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ResourceGroupGroup", L"ResourceGroup 그룹", L"#AWS #Cloud #Cluster #Group #Infrastructure #Logical #Tag6 #Tag7 #Tag8 #Tag9 #AWS #그룹 #논리 #인프라 #클라우드 #클러스터 #태그6 #태그7 #태그8 #태그9" },
    { L"RoboMakerRobotApplication", L"RoboMakerRobot 애플리케이션", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"RoboMakerSimulationApplication", L"RoboMakerSimulation 애플리케이션", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"RoboMakerSimulationJob", L"RoboMakerSimulationJob", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"Route53HealthCheck", L"Route53 HealthCheck", L"#AWS #Cloud #DNS #Domain #Infrastructure #Network #Route #Tag7 #Tag8 #Tag9 #AWS #DNS #네트워크 #도메인 #라우팅 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"Route53HostedZone", L"Route 53 호스팅 영역", L"#AWS #Cloud #DNS #Domain #Infrastructure #Network #Route #Tag7 #Tag8 #Tag9 #AWS #DNS #네트워크 #도메인 #라우팅 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"Route53ResolverEndpoint", L"Route53 ResolverEndpoint", L"#AWS #Cloud #DNS #Domain #Infrastructure #Network #Route #Tag7 #Tag8 #Tag9 #AWS #DNS #네트워크 #도메인 #라우팅 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"Route53ResolverRule", L"Route53 ResolverRule", L"#AWS #Cloud #DNS #Domain #Infrastructure #Network #Route #Tag7 #Tag8 #Tag9 #AWS #DNS #네트워크 #도메인 #라우팅 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"Route53ResourceRecordSet", L"Route53 ResourceRecordSet", L"#AWS #Cloud #DNS #Domain #Infrastructure #Network #Route #Tag7 #Tag8 #Tag9 #AWS #DNS #네트워크 #도메인 #라우팅 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"Route53TrafficPolicy", L"Route53 Traffic 정책", L"#AWS #Cloud #DNS #Domain #Infrastructure #Network #Permission #Policy #Route #Rule #AWS #DNS #권한 #규칙 #네트워크 #도메인 #라우팅 #인프라 #정책 #클라우드" },
    { L"S3AccessPoint", L"S3 액세스 포인트", L"#AWS #Bucket #Cloud #File #Infrastructure #Object #Storage #Tag7 #Tag8 #Tag9 #AWS #객체 #버킷 #스토리지 #인프라 #클라우드 #태그7 #태그8 #태그9 #파일" },
    { L"S3MultipartUpload", L"S3 MultipartUpload", L"#AWS #Bucket #Cloud #File #Infrastructure #Object #Storage #Tag7 #Tag8 #Tag9 #AWS #객체 #버킷 #스토리지 #인프라 #클라우드 #태그7 #태그8 #태그9 #파일" },
    { L"S3Object", L"S3 객체 (파일)", L"#AWS #Bucket #Cloud #File #Infrastructure #Object #Storage #Tag7 #Tag8 #Tag9 #AWS #객체 #버킷 #스토리지 #인프라 #클라우드 #태그7 #태그8 #태그9 #파일" },
    { L"SESConfigurationSet", L"SESConfigurationSet", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SESIdentity", L"SESIdentity", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SESReceiptFilter", L"SESReceiptFilter", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SESReceiptRuleSet", L"SESReceiptRuleSet", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SESTemplate", L"SESTemplate", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SFNStateMachine", L"SFNStateMachine", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SNSEndpoint", L"SNS Endpoint", L"#AWS #Alert #Cloud #Infrastructure #Messaging #Notification #PubSub #Tag7 #Tag8 #Tag9 #AWS #메시징 #발행구독 #알림 #인프라 #클라우드 #태그7 #태그8 #태그9 #푸시" },
    { L"SNSPlatformApplication", L"SNS Platform 애플리케이션", L"#AWS #Alert #Cloud #Infrastructure #Messaging #Notification #PubSub #Tag7 #Tag8 #Tag9 #AWS #메시징 #발행구독 #알림 #인프라 #클라우드 #태그7 #태그8 #태그9 #푸시" },
    { L"SNSSubscription", L"SNS Subscription", L"#AWS #Alert #Cloud #Infrastructure #Messaging #Notification #PubSub #Tag7 #Tag8 #Tag9 #AWS #메시징 #발행구독 #알림 #인프라 #클라우드 #태그7 #태그8 #태그9 #푸시" },
    { L"SNSTopic", L"SNS 토픽", L"#AWS #Alert #Cloud #Infrastructure #Messaging #Notification #PubSub #Tag7 #Tag8 #Tag9 #AWS #메시징 #발행구독 #알림 #인프라 #클라우드 #태그7 #태그8 #태그9 #푸시" },
    { L"SQSQueue", L"SQS 대기열", L"#AWS #Async #Cloud #Decoupled #Infrastructure #Messaging #Queue #Tag7 #Tag8 #Tag9 #AWS #대기열 #디커플링 #메시징 #비동기 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"SSMActivation", L"SSMActivation", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SSMAssociation", L"SSMAssociation", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SSMDocument", L"SSMDocument", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SSMMaintenanceWindow", L"SSMMaintenanceWindow", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SSMParameter", L"SSMParameter", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SSMPatchBaseline", L"SSMPatchBaseline", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SSMResourceDataSync", L"SSMResourceDataSync", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SageMakerApp", L"SageMakerApp", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SageMakerDomain", L"SageMaker 도메인", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SageMakerEndpoint", L"SageMakerEndpoint", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SageMakerEndpointConfig", L"SageMakerEndpoint 설정", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SageMakerModel", L"SageMakerModel", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SageMakerNotebookInstance", L"SageMakerNotebook 인스턴스", L"#AWS #Cloud #Computing #Infrastructure #Instance #Runtime #Tag6 #Tag7 #Tag8 #Tag9 #AWS #실행환경 #인스턴스 #인프라 #컴퓨팅 #클라우드 #태그6 #태그7 #태그8 #태그9" },
    { L"SageMakerNotebookInstanceLifecycleConfig", L"SageMakerNotebookInstanceLifecycle 설정", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SageMakerNotebookInstanceState", L"SageMakerNotebookInstanceState", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SageMakerUserProfiles", L"SageMakerUserProfiles", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SecretsManagerSecret", L"SecretsManager 시크릿", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SecurityHub", L"SecurityHub", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ServiceCatalogConstraintPortfolioAttachment", L"ServiceCatalogConstraintPortfolioAttachment", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ServiceCatalogPortfolio", L"ServiceCatalogPortfolio", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ServiceCatalogPortfolioProductAttachment", L"ServiceCatalogPortfolioProductAttachment", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ServiceCatalogPortfolioShareAttachment", L"ServiceCatalogPortfolioShareAttachment", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ServiceCatalogPrincipalPortfolioAttachment", L"ServiceCatalogPrincipalPortfolioAttachment", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ServiceCatalogProduct", L"ServiceCatalogProduct", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ServiceCatalogProvisionedProduct", L"ServiceCatalogProvisionedProduct", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ServiceCatalogTagOption", L"ServiceCatalogTagOption", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ServiceCatalogTagOptionPortfolioAttachment", L"ServiceCatalogTagOptionPortfolioAttachment", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ServiceDiscoveryInstance", L"ServiceDiscovery 인스턴스", L"#AWS #Cloud #Computing #Infrastructure #Instance #Runtime #Tag6 #Tag7 #Tag8 #Tag9 #AWS #실행환경 #인스턴스 #인프라 #컴퓨팅 #클라우드 #태그6 #태그7 #태그8 #태그9" },
    { L"ServiceDiscoveryNamespace", L"ServiceDiscoveryNamespace", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"ServiceDiscoveryService", L"ServiceDiscovery 서비스", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SignerSigningJob", L"SignerSigningJob", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"SimpleDBDomain", L"SimpleDB 도메인", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"StorageGatewayFileShare", L"StorageGatewayFileShare", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"StorageGatewayGateway", L"StorageGateway 게이트웨이", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"StorageGatewayTape", L"StorageGatewayTape", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"StorageGatewayVolume", L"StorageGateway 볼륨", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"TransferServer", L"TransferServer", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"TransferServerUser", L"TransferServer 사용자", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"WAFRegionalByteMatchSet", L"WAFRegionalByteMatchSet", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFRegionalByteMatchSetIP", L"WAFRegionalByteMatchSetIP", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFRegionalIPSet", L"WAFRegionalIPSet", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFRegionalIPSetIP", L"WAFRegionalIPSetIP", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFRegionalRateBasedRule", L"WAFRegionalRateBasedRule", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFRegionalRateBasedRulePredicate", L"WAFRegionalRateBasedRulePredicate", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFRegionalRegexMatchSet", L"WAFRegionalRegexMatchSet", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFRegionalRegexMatchTuple", L"WAFRegionalRegexMatchTuple", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFRegionalRegexPatternSet", L"WAFRegionalRegexPatternSet", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFRegionalRegexPatternString", L"WAFRegionalRegexPatternString", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFRegionalRule", L"WAFRegionalRule", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFRegionalRuleGroup", L"WAFRegionalRule 그룹", L"#AWS #Cloud #Cluster #Firewall #Group #Infrastructure #Logical #Network #Security #Web #AWS #그룹 #네트워크 #논리 #방화벽 #보안 #웹 #인프라 #클라우드 #클러스터" },
    { L"WAFRegionalRulePredicate", L"WAFRegionalRulePredicate", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFRegionalWebACL", L"WAFRegionalWebACL", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFRegionalWebACLRuleAttachment", L"WAFRegionalWebACLRuleAttachment", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFRule", L"WAFRule", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFWebACL", L"WAFWebACL", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFWebACLRuleAttachment", L"WAFWebACLRuleAttachment", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFv2IPSet", L"WAFv2IPSet", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFv2RegexPatternSet", L"WAFv2RegexPatternSet", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WAFv2RuleGroup", L"WAFv2Rule 그룹", L"#AWS #Cloud #Cluster #Firewall #Group #Infrastructure #Logical #Network #Security #Web #AWS #그룹 #네트워크 #논리 #방화벽 #보안 #웹 #인프라 #클라우드 #클러스터" },
    { L"WAFv2WebACL", L"WAFv2WebACL", L"#AWS #Cloud #Firewall #Infrastructure #Network #Security #Tag7 #Tag8 #Tag9 #Web #AWS #네트워크 #방화벽 #보안 #웹 #인프라 #클라우드 #태그7 #태그8 #태그9" },
    { L"WorkSpacesWorkspace", L"WorkSpacesWorkspace", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
    { L"XRayGroup", L"XRay 그룹", L"#AWS #Cloud #Cluster #Group #Infrastructure #Logical #Tag6 #Tag7 #Tag8 #Tag9 #AWS #그룹 #논리 #인프라 #클라우드 #클러스터 #태그6 #태그7 #태그8 #태그9" },
    { L"XRaySamplingRule", L"XRaySamplingRule", L"#AWS #Cloud #Infrastructure #Tag3 #Tag4 #Tag5 #Tag6 #Tag7 #Tag8 #Tag9 #AWS #인프라 #클라우드 #태그3 #태그4 #태그5 #태그6 #태그7 #태그8 #태그9" },
};
const int g_numResourceTypes = sizeof(g_resourceInfos) / sizeof(g_resourceInfos[0]);

#endif
