#ifndef RESOURCE_LIST_H
#define RESOURCE_LIST_H

struct ResourceInfo {
    const wchar_t* eng;
    const wchar_t* kor;
};

const ResourceInfo g_resourceInfos[] = {
    { L"<모두>", L"모든 리소스" },
    { L"EC2Instance", L"EC2 인스턴스" },
    { L"EC2VPC", L"VPC (가상 네트워크)" },
    { L"IAMUser", L"IAM 사용자" },
    { L"LambdaFunction", L"Lambda 함수" },
    { L"RDSInstance", L"RDS 데이터베이스" },
    { L"S3Bucket", L"S3 버킷" },
    { L"ACMCertificate", L"ACM 인증서" },
    { L"ACMPCACertificateAuthority", L"ACM PCACertificateAuthority" },
    { L"ACMPCACertificateAuthorityState", L"ACM PCACertificateAuthorityState" },
    { L"AMGWorkspace", L"AMGWorkspace" },
    { L"AMPWorkspace", L"AMPWorkspace" },
    { L"APIGatewayAPIKey", L"APIGatewayAPIKey" },
    { L"APIGatewayClientCertificate", L"APIGatewayClient 인증서" },
    { L"APIGatewayDomainName", L"APIGatewayDomainName" },
    { L"APIGatewayRestAPI", L"APIGatewayRestAPI" },
    { L"APIGatewayUsagePlan", L"APIGatewayUsagePlan" },
    { L"APIGatewayV2API", L"APIGatewayV2API" },
    { L"APIGatewayV2VpcLink", L"APIGatewayV2 VPC 링크" },
    { L"APIGatewayVpcLink", L"APIGateway VPC 링크" },
    { L"AWS::AppFlow::ConnectorProfile", L"AWS::AppFlow::ConnectorProfile" },
    { L"AWS::AppFlow::Flow", L"AWS::AppFlow::Flow" },
    { L"AWS::AppRunner::Service", L"AWS::AppRunner:: 서비스" },
    { L"AWS::ApplicationInsights::Application", L"AWS::ApplicationInsights:: 애플리케이션" },
    { L"AWS::Backup::Framework", L"AWS::Backup::Framework" },
    { L"AWS::ECR::PublicRepository", L"AWS::ECR::Public 저장소" },
    { L"AWS::ECR::PullThroughCacheRule", L"AWS::ECR::PullThroughCacheRule" },
    { L"AWS::ECR::RegistryPolicy", L"AWS::ECR::Registry 정책" },
    { L"AWS::ECR::ReplicationConfiguration", L"AWS::ECR::ReplicationConfiguration" },
    { L"AWS::MWAA::Environment", L"AWS::MWAA:: 환경" },
    { L"AWS::NetworkFirewall::Firewall", L"AWS::NetworkFirewall::Firewall" },
    { L"AWS::NetworkFirewall::FirewallPolicy", L"AWS::NetworkFirewall::Firewall 정책" },
    { L"AWS::NetworkFirewall::RuleGroup", L"AWS::NetworkFirewall::Rule 그룹" },
    { L"AWS::Synthetics::Canary", L"AWS::Synthetics::Canary" },
    { L"AWS::Timestream::Database", L"AWS::Timestream:: 데이터베이스" },
    { L"AWS::Timestream::ScheduledQuery", L"AWS::Timestream::ScheduledQuery" },
    { L"AWS::Timestream::Table", L"AWS::Timestream:: 테이블" },
    { L"AWS::Transfer::Workflow", L"AWS::Transfer::Workflow" },
    { L"AWSBackupPlan", L"AWSBackupPlan" },
    { L"AWSBackupRecoveryPoint", L"AWSBackupRecoveryPoint" },
    { L"AWSBackupSelection", L"AWSBackupSelection" },
    { L"AWSBackupVault", L"AWSBackupVault" },
    { L"AWSBackupVaultAccessPolicy", L"AWSBackupVaultAccess 정책" },
    { L"AccessAnalyzer", L"AccessAnalyzer" },
    { L"AppMeshGatewayRoute", L"AppMeshGatewayRoute" },
    { L"AppMeshMesh", L"AppMeshMesh" },
    { L"AppMeshRoute", L"AppMeshRoute" },
    { L"AppMeshVirtualGateway", L"AppMeshVirtual 게이트웨이" },
    { L"AppMeshVirtualNode", L"AppMeshVirtualNode" },
    { L"AppMeshVirtualRouter", L"AppMeshVirtualRouter" },
    { L"AppMeshVirtualService", L"AppMeshVirtual 서비스" },
    { L"AppStreamDirectoryConfig", L"AppStreamDirectory 설정" },
    { L"AppStreamFleet", L"AppStreamFleet" },
    { L"AppStreamFleetState", L"AppStreamFleetState" },
    { L"AppStreamImage", L"AppStream 이미지" },
    { L"AppStreamImageBuilder", L"AppStreamImageBuilder" },
    { L"AppStreamImageBuilderWaiter", L"AppStreamImageBuilderWaiter" },
    { L"AppStreamStack", L"AppStream 스택" },
    { L"AppStreamStackFleetAttachment", L"AppStreamStackFleetAttachment" },
    { L"AppSyncGraphqlAPI", L"AppSyncGraphqlAPI" },
    { L"ApplicationAutoScalingScalableTarget", L"ApplicationAutoScalingScalableTarget" },
    { L"ArchiveRule", L"ArchiveRule" },
    { L"AthenaNamedQuery", L"AthenaNamedQuery" },
    { L"AthenaWorkGroup", L"AthenaWork 그룹" },
    { L"AutoScalingGroup", L"AutoScaling 그룹" },
    { L"AutoScalingPlansScalingPlan", L"AutoScalingPlansScalingPlan" },
    { L"BatchComputeEnvironment", L"BatchCompute 환경" },
    { L"BatchComputeEnvironmentState", L"BatchComputeEnvironmentState" },
    { L"BatchJobQueue", L"BatchJob 큐(대기열)" },
    { L"BatchJobQueueState", L"BatchJobQueueState" },
    { L"BillingCostandUsageReport", L"BillingCostandUsageReport" },
    { L"Budget", L"Budget" },
    { L"Cloud9Environment", L"Cloud9 환경" },
    { L"CloudDirectoryDirectory", L"CloudDirectoryDirectory" },
    { L"CloudDirectorySchema", L"CloudDirectorySchema" },
    { L"CloudFormationStack", L"CloudFormation 스택" },
    { L"CloudFormationStackSet", L"CloudFormationStackSet" },
    { L"CloudFormationType", L"CloudFormationType" },
    { L"CloudFrontDistribution", L"CloudFront 배포(CDN)" },
    { L"CloudFrontDistributionDeployment", L"CloudFrontDistributionDeployment" },
    { L"CloudFrontOriginAccessIdentity", L"CloudFrontOriginAccessIdentity" },
    { L"CloudHSMV2Cluster", L"CloudHSMV2 클러스터" },
    { L"CloudHSMV2ClusterHSM", L"CloudHSMV2ClusterHSM" },
    { L"CloudSearchDomain", L"CloudSearch 도메인" },
    { L"CloudTrailTrail", L"CloudTrailTrail" },
    { L"CloudWatchAlarm", L"CloudWatch 알람" },
    { L"CloudWatchDashboard", L"CloudWatch Dashboard" },
    { L"CloudWatchEventsBuses", L"CloudWatch EventsBuses" },
    { L"CloudWatchEventsRule", L"CloudWatch EventsRule" },
    { L"CloudWatchEventsTarget", L"CloudWatch EventsTarget" },
    { L"CloudWatchLogsDestination", L"CloudWatch LogsDestination" },
    { L"CloudWatchLogsLogGroup", L"CloudWatch 로그 그룹" },
    { L"CloudWatchLogsResourcePolicy", L"CloudWatch LogsResource 정책" },
    { L"CodeArtifactDomain", L"CodeArtifact 도메인" },
    { L"CodeArtifactRepository", L"CodeArtifact 저장소" },
    { L"CodeBuildProject", L"CodeBuild 프로젝트" },
    { L"CodeCommitRepository", L"CodeCommit 저장소" },
    { L"CodeDeployApplication", L"CodeDeploy 애플리케이션" },
    { L"CodePipelinePipeline", L"CodePipeline 파이프라인" },
    { L"CodeStarConnection", L"CodeStar 연결" },
    { L"CodeStarNotificationRule", L"CodeStarNotificationRule" },
    { L"CodeStarProject", L"CodeStar 프로젝트" },
    { L"CognitoIdentityPool", L"CognitoIdentityPool" },
    { L"CognitoIdentityProvider", L"CognitoIdentityProvider" },
    { L"CognitoUserPool", L"CognitoUserPool" },
    { L"CognitoUserPoolClient", L"CognitoUserPoolClient" },
    { L"CognitoUserPoolDomain", L"CognitoUserPool 도메인" },
    { L"ComprehendDocumentClassifier", L"ComprehendDocumentClassifier" },
    { L"ComprehendDominantLanguageDetectionJob", L"ComprehendDominantLanguageDetectionJob" },
    { L"ComprehendEndpoint", L"ComprehendEndpoint" },
    { L"ComprehendEntitiesDetectionJob", L"ComprehendEntitiesDetectionJob" },
    { L"ComprehendEntityRecognizer", L"ComprehendEntityRecognizer" },
    { L"ComprehendKeyPhrasesDetectionJob", L"ComprehendKeyPhrasesDetectionJob" },
    { L"ComprehendSentimentDetectionJob", L"ComprehendSentimentDetectionJob" },
    { L"ConfigServiceConfigRule", L"ConfigServiceConfigRule" },
    { L"ConfigServiceConfigurationRecorder", L"ConfigServiceConfigurationRecorder" },
    { L"ConfigServiceDeliveryChannel", L"ConfigServiceDeliveryChannel" },
    { L"DAXCluster", L"DAX 클러스터" },
    { L"DAXParameterGroup", L"DAXParameter 그룹" },
    { L"DAXSubnetGroup", L"DAXSubnet 그룹" },
    { L"DataPipelinePipeline", L"DataPipeline 파이프라인" },
    { L"DatabaseMigrationServiceCertificate", L"DatabaseMigrationService 인증서" },
    { L"DatabaseMigrationServiceEndpoint", L"DatabaseMigrationServiceEndpoint" },
    { L"DatabaseMigrationServiceEventSubscription", L"DatabaseMigrationServiceEventSubscription" },
    { L"DatabaseMigrationServiceReplicationInstance", L"DatabaseMigrationServiceReplication 인스턴스" },
    { L"DatabaseMigrationServiceReplicationTask", L"DatabaseMigrationServiceReplicationTask" },
    { L"DatabaseMigrationServiceSubnetGroup", L"DatabaseMigrationServiceSubnet 그룹" },
    { L"DeviceFarmProject", L"DeviceFarm 프로젝트" },
    { L"DirectoryServiceDirectory", L"DirectoryServiceDirectory" },
    { L"DynamoDBTable", L"DynamoDB 테이블" },
    { L"DynamoDBTableItem", L"DynamoDBTableItem" },
    { L"EC2Address", L"EC2 공인 IP(EIP)" },
    { L"EC2ClientVpnEndpoint", L"EC2 ClientVpnEndpoint" },
    { L"EC2ClientVpnEndpointAttachment", L"EC2 ClientVpnEndpointAttachment" },
    { L"EC2CustomerGateway", L"EC2 Customer 게이트웨이" },
    { L"EC2DHCPOption", L"EC2 DHCPOption" },
    { L"EC2DefaultSecurityGroupRule", L"EC2 DefaultSecurityGroupRule" },
    { L"EC2EgressOnlyInternetGateway", L"EC2 EgressOnlyInternet 게이트웨이" },
    { L"EC2Host", L"EC2 Host" },
    { L"EC2Image", L"EC2 이미지" },
    { L"EC2InternetGateway", L"인터넷 게이트웨이" },
    { L"EC2InternetGatewayAttachment", L"EC2 InternetGatewayAttachment" },
    { L"EC2KeyPair", L"EC2 키 페어" },
    { L"EC2LaunchTemplate", L"EC2 LaunchTemplate" },
    { L"EC2NATGateway", L"EC2 NAT 게이트웨이" },
    { L"EC2NetworkACL", L"EC2 NetworkACL" },
    { L"EC2NetworkInterface", L"EC2 네트워크 인터페이스 (ENI)" },
    { L"EC2PlacementGroup", L"EC2 Placement 그룹" },
    { L"EC2RouteTable", L"라우팅 테이블" },
    { L"EC2SecurityGroup", L"보안 그룹" },
    { L"EC2Snapshot", L"EBS 스냅샷" },
    { L"EC2SpotFleetRequest", L"EC2 SpotFleetRequest" },
    { L"EC2Subnet", L"VPC 서브넷" },
    { L"EC2TGW", L"EC2 TGW" },
    { L"EC2TGWAttachment", L"EC2 TGWAttachment" },
    { L"EC2VPCEndpoint", L"EC2 VPCEndpoint" },
    { L"EC2VPCEndpointConnection", L"EC2 VPCEndpoint 연결" },
    { L"EC2VPCEndpointServiceConfiguration", L"EC2 VPCEndpointServiceConfiguration" },
    { L"EC2VPCPeeringConnection", L"EC2 VPCPeering 연결" },
    { L"EC2VPNConnection", L"EC2 VPN 연결" },
    { L"EC2VPNGateway", L"EC2 VPN 게이트웨이" },
    { L"EC2VPNGatewayAttachment", L"EC2 VPNGatewayAttachment" },
    { L"EC2Volume", L"EBS 볼륨" },
    { L"ECRRepository", L"ECR 저장소" },
    { L"ECSCluster", L"ECS 클러스터" },
    { L"ECSClusterInstance", L"ECS Cluster 인스턴스" },
    { L"ECSService", L"ECS 서비스" },
    { L"ECSTask", L"ECS Task" },
    { L"ECSTaskDefinition", L"ECS TaskDefinition" },
    { L"EFSFileSystem", L"EFSFileSystem" },
    { L"EFSMountTarget", L"EFSMountTarget" },
    { L"EKSCluster", L"EKS 클러스터" },
    { L"EKSFargateProfiles", L"EKS FargateProfiles" },
    { L"EKSNodegroups", L"EKS Nodegroups" },
    { L"ELB", L"Classic 로드 밸런서" },
    { L"ELBv2", L"Application/Network 로드 밸런서" },
    { L"ELBv2TargetGroup", L"ELBv2Target 그룹" },
    { L"EMRCluster", L"EMR 클러스터" },
    { L"EMRSecurityConfiguration", L"EMRSecurityConfiguration" },
    { L"ESDomain", L"ES 도메인" },
    { L"ElasticBeanstalkApplication", L"ElasticBeanstalk 애플리케이션" },
    { L"ElasticBeanstalkEnvironment", L"ElasticBeanstalk 환경" },
    { L"ElasticTranscoderPipeline", L"ElasticTranscoder 파이프라인" },
    { L"ElasticacheCacheCluster", L"ElasticacheCache 클러스터" },
    { L"ElasticacheCacheParameterGroup", L"ElasticacheCacheParameter 그룹" },
    { L"ElasticacheReplicationGroup", L"ElasticacheReplication 그룹" },
    { L"ElasticacheSubnetGroup", L"ElasticacheSubnet 그룹" },
    { L"FMSNotificationChannel", L"FMSNotificationChannel" },
    { L"FMSPolicy", L"FMS 정책" },
    { L"FSxBackup", L"FSxBackup" },
    { L"FSxFileSystem", L"FSxFileSystem" },
    { L"FirehoseDeliveryStream", L"FirehoseDeliveryStream" },
    { L"GlobalAccelerator", L"GlobalAccelerator" },
    { L"GlobalAcceleratorEndpointGroup", L"GlobalAcceleratorEndpoint 그룹" },
    { L"GlobalAcceleratorListener", L"GlobalAcceleratorListener" },
    { L"GlueClassifier", L"GlueClassifier" },
    { L"GlueConnection", L"Glue 연결" },
    { L"GlueCrawler", L"GlueCrawler" },
    { L"GlueDataBrewDatasets", L"GlueDataBrewDatasets" },
    { L"GlueDataBrewJobs", L"GlueDataBrewJobs" },
    { L"GlueDataBrewProjects", L"GlueDataBrewProjects" },
    { L"GlueDataBrewRecipe", L"GlueDataBrewRecipe" },
    { L"GlueDataBrewRulesets", L"GlueDataBrewRulesets" },
    { L"GlueDataBrewSchedules", L"GlueDataBrewSchedules" },
    { L"GlueDatabase", L"Glue 데이터베이스" },
    { L"GlueDevEndpoint", L"GlueDevEndpoint" },
    { L"GlueJob", L"GlueJob" },
    { L"GlueTrigger", L"GlueTrigger" },
    { L"GuardDutyDetector", L"GuardDutyDetector" },
    { L"IAMGroup", L"IAM 그룹" },
    { L"IAMGroupPolicy", L"IAM Group 정책" },
    { L"IAMGroupPolicyAttachment", L"IAM GroupPolicyAttachment" },
    { L"IAMInstanceProfile", L"IAM InstanceProfile" },
    { L"IAMInstanceProfileRole", L"IAM InstanceProfile 역할" },
    { L"IAMLoginProfile", L"IAM LoginProfile" },
    { L"IAMOpenIDConnectProvider", L"IAM OpenIDConnectProvider" },
    { L"IAMPolicy", L"IAM 정책" },
    { L"IAMRole", L"IAM 역할" },
    { L"IAMRolePolicy", L"IAM Role 정책" },
    { L"IAMRolePolicyAttachment", L"IAM RolePolicyAttachment" },
    { L"IAMSAMLProvider", L"IAM SAMLProvider" },
    { L"IAMServerCertificate", L"IAM Server 인증서" },
    { L"IAMServiceSpecificCredential", L"IAM ServiceSpecificCredential" },
    { L"IAMSigningCertificate", L"IAM Signing 인증서" },
    { L"IAMUserAccessKey", L"IAM UserAccessKey" },
    { L"IAMUserGroupAttachment", L"IAM UserGroupAttachment" },
    { L"IAMUserPolicy", L"IAM User 정책" },
    { L"IAMUserPolicyAttachment", L"IAM UserPolicyAttachment" },
    { L"IAMUserSSHPublicKey", L"IAM UserSSHPublicKey" },
    { L"IAMVirtualMFADevice", L"IAM VirtualMFADevice" },
    { L"ImageBuilderComponent", L"ImageBuilderComponent" },
    { L"ImageBuilderDistributionConfiguration", L"ImageBuilderDistributionConfiguration" },
    { L"ImageBuilderImage", L"ImageBuilder 이미지" },
    { L"ImageBuilderInfrastructureConfiguration", L"ImageBuilderInfrastructureConfiguration" },
    { L"ImageBuilderPipeline", L"ImageBuilder 파이프라인" },
    { L"ImageBuilderRecipe", L"ImageBuilderRecipe" },
    { L"Inspector2", L"Inspector2" },
    { L"InspectorAssessmentRun", L"InspectorAssessmentRun" },
    { L"InspectorAssessmentTarget", L"InspectorAssessmentTarget" },
    { L"InspectorAssessmentTemplate", L"InspectorAssessmentTemplate" },
    { L"IoTAuthorizer", L"IoTAuthorizer" },
    { L"IoTCACertificate", L"IoTCA 인증서" },
    { L"IoTCertificate", L"IoT 인증서" },
    { L"IoTJob", L"IoTJob" },
    { L"IoTOTAUpdate", L"IoTOTAUpdate" },
    { L"IoTPolicy", L"IoT 정책" },
    { L"IoTRoleAlias", L"IoTRoleAlias" },
    { L"IoTStream", L"IoTStream" },
    { L"IoTThing", L"IoTThing" },
    { L"IoTThingGroup", L"IoTThing 그룹" },
    { L"IoTThingType", L"IoTThingType" },
    { L"IoTThingTypeState", L"IoTThingTypeState" },
    { L"IoTTopicRule", L"IoTTopicRule" },
    { L"KMSAlias", L"KMS Alias" },
    { L"KMSKey", L"KMS Key" },
    { L"KendraIndex", L"KendraIndex" },
    { L"KinesisAnalyticsApplication", L"KinesisAnalytics 애플리케이션" },
    { L"KinesisStream", L"KinesisStream" },
    { L"KinesisVideoProject", L"KinesisVideo 프로젝트" },
    { L"LambdaEventSourceMapping", L"Lambda EventSourceMapping" },
    { L"LambdaLayer", L"Lambda Layer" },
    { L"LaunchConfiguration", L"LaunchConfiguration" },
    { L"LexBot", L"LexBot" },
    { L"LexIntent", L"LexIntent" },
    { L"LexModelBuildingServiceBotAlias", L"LexModelBuildingServiceBotAlias" },
    { L"LexSlotType", L"LexSlotType" },
    { L"LifecycleHook", L"LifecycleHook" },
    { L"LightsailDisk", L"LightsailDisk" },
    { L"LightsailDomain", L"Lightsail 도메인" },
    { L"LightsailInstance", L"Lightsail 인스턴스" },
    { L"LightsailKeyPair", L"Lightsail 키 페어" },
    { L"LightsailLoadBalancer", L"Lightsail 로드 밸런서" },
    { L"LightsailStaticIP", L"LightsailStaticIP" },
    { L"MQBroker", L"MQBroker" },
    { L"MSKCluster", L"MSK 클러스터" },
    { L"MSKConfiguration", L"MSKConfiguration" },
    { L"MachineLearningBranchPrediction", L"MachineLearningBranchPrediction" },
    { L"MachineLearningDataSource", L"MachineLearningDataSource" },
    { L"MachineLearningEvaluation", L"MachineLearningEvaluation" },
    { L"MachineLearningMLModel", L"MachineLearningMLModel" },
    { L"Macie", L"Macie" },
    { L"MediaConvertJobTemplate", L"MediaConvertJobTemplate" },
    { L"MediaConvertPreset", L"MediaConvertPreset" },
    { L"MediaConvertQueue", L"MediaConvert 큐(대기열)" },
    { L"MediaLiveChannel", L"MediaLiveChannel" },
    { L"MediaLiveInput", L"MediaLiveInput" },
    { L"MediaLiveInputSecurityGroup", L"MediaLiveInputSecurity 그룹" },
    { L"MediaPackageChannel", L"MediaPackageChannel" },
    { L"MediaPackageOriginEndpoint", L"MediaPackageOriginEndpoint" },
    { L"MediaStoreContainer", L"MediaStoreContainer" },
    { L"MediaStoreDataItems", L"MediaStoreDataItems" },
    { L"MediaTailorConfiguration", L"MediaTailorConfiguration" },
    { L"MobileProject", L"Mobile 프로젝트" },
    { L"NeptuneCluster", L"Neptune 클러스터" },
    { L"NeptuneInstance", L"Neptune 인스턴스" },
    { L"NetpuneSnapshot", L"Netpune 스냅샷" },
    { L"OSDomain", L"OS 도메인" },
    { L"OpsWorksApp", L"OpsWorksApp" },
    { L"OpsWorksCMBackup", L"OpsWorksCMBackup" },
    { L"OpsWorksCMServer", L"OpsWorksCMServer" },
    { L"OpsWorksCMServerState", L"OpsWorksCMServerState" },
    { L"OpsWorksInstance", L"OpsWorks 인스턴스" },
    { L"OpsWorksLayer", L"OpsWorksLayer" },
    { L"OpsWorksUserProfile", L"OpsWorksUserProfile" },
    { L"QLDBLedger", L"QLDBLedger" },
    { L"RDSClusterSnapshot", L"RDS Cluster 스냅샷" },
    { L"RDSDBCluster", L"RDS DB 클러스터" },
    { L"RDSDBClusterParameterGroup", L"RDS DBClusterParameter 그룹" },
    { L"RDSDBParameterGroup", L"RDS DBParameter 그룹" },
    { L"RDSDBSubnetGroup", L"RDS DBSubnet 그룹" },
    { L"RDSEventSubscription", L"RDS EventSubscription" },
    { L"RDSOptionGroup", L"RDS Option 그룹" },
    { L"RDSProxy", L"RDS Proxy" },
    { L"RDSSnapshot", L"RDS 스냅샷" },
    { L"RedshiftCluster", L"Redshift 클러스터" },
    { L"RedshiftParameterGroup", L"RedshiftParameter 그룹" },
    { L"RedshiftSnapshot", L"Redshift 스냅샷" },
    { L"RedshiftSubnetGroup", L"RedshiftSubnet 그룹" },
    { L"RekognitionCollection", L"RekognitionCollection" },
    { L"ResourceGroupGroup", L"ResourceGroup 그룹" },
    { L"RoboMakerRobotApplication", L"RoboMakerRobot 애플리케이션" },
    { L"RoboMakerSimulationApplication", L"RoboMakerSimulation 애플리케이션" },
    { L"RoboMakerSimulationJob", L"RoboMakerSimulationJob" },
    { L"Route53HealthCheck", L"Route53 HealthCheck" },
    { L"Route53HostedZone", L"Route 53 호스팅 영역" },
    { L"Route53ResolverEndpoint", L"Route53 ResolverEndpoint" },
    { L"Route53ResolverRule", L"Route53 ResolverRule" },
    { L"Route53ResourceRecordSet", L"Route53 ResourceRecordSet" },
    { L"Route53TrafficPolicy", L"Route53 Traffic 정책" },
    { L"S3AccessPoint", L"S3 액세스 포인트" },
    { L"S3MultipartUpload", L"S3 MultipartUpload" },
    { L"S3Object", L"S3 객체 (파일)" },
    { L"SESConfigurationSet", L"SESConfigurationSet" },
    { L"SESIdentity", L"SESIdentity" },
    { L"SESReceiptFilter", L"SESReceiptFilter" },
    { L"SESReceiptRuleSet", L"SESReceiptRuleSet" },
    { L"SESTemplate", L"SESTemplate" },
    { L"SFNStateMachine", L"SFNStateMachine" },
    { L"SNSEndpoint", L"SNS Endpoint" },
    { L"SNSPlatformApplication", L"SNS Platform 애플리케이션" },
    { L"SNSSubscription", L"SNS Subscription" },
    { L"SNSTopic", L"SNS 토픽" },
    { L"SQSQueue", L"SQS 대기열" },
    { L"SSMActivation", L"SSMActivation" },
    { L"SSMAssociation", L"SSMAssociation" },
    { L"SSMDocument", L"SSMDocument" },
    { L"SSMMaintenanceWindow", L"SSMMaintenanceWindow" },
    { L"SSMParameter", L"SSMParameter" },
    { L"SSMPatchBaseline", L"SSMPatchBaseline" },
    { L"SSMResourceDataSync", L"SSMResourceDataSync" },
    { L"SageMakerApp", L"SageMakerApp" },
    { L"SageMakerDomain", L"SageMaker 도메인" },
    { L"SageMakerEndpoint", L"SageMakerEndpoint" },
    { L"SageMakerEndpointConfig", L"SageMakerEndpoint 설정" },
    { L"SageMakerModel", L"SageMakerModel" },
    { L"SageMakerNotebookInstance", L"SageMakerNotebook 인스턴스" },
    { L"SageMakerNotebookInstanceLifecycleConfig", L"SageMakerNotebookInstanceLifecycle 설정" },
    { L"SageMakerNotebookInstanceState", L"SageMakerNotebookInstanceState" },
    { L"SageMakerUserProfiles", L"SageMakerUserProfiles" },
    { L"SecretsManagerSecret", L"SecretsManager 시크릿" },
    { L"SecurityHub", L"SecurityHub" },
    { L"ServiceCatalogConstraintPortfolioAttachment", L"ServiceCatalogConstraintPortfolioAttachment" },
    { L"ServiceCatalogPortfolio", L"ServiceCatalogPortfolio" },
    { L"ServiceCatalogPortfolioProductAttachment", L"ServiceCatalogPortfolioProductAttachment" },
    { L"ServiceCatalogPortfolioShareAttachment", L"ServiceCatalogPortfolioShareAttachment" },
    { L"ServiceCatalogPrincipalPortfolioAttachment", L"ServiceCatalogPrincipalPortfolioAttachment" },
    { L"ServiceCatalogProduct", L"ServiceCatalogProduct" },
    { L"ServiceCatalogProvisionedProduct", L"ServiceCatalogProvisionedProduct" },
    { L"ServiceCatalogTagOption", L"ServiceCatalogTagOption" },
    { L"ServiceCatalogTagOptionPortfolioAttachment", L"ServiceCatalogTagOptionPortfolioAttachment" },
    { L"ServiceDiscoveryInstance", L"ServiceDiscovery 인스턴스" },
    { L"ServiceDiscoveryNamespace", L"ServiceDiscoveryNamespace" },
    { L"ServiceDiscoveryService", L"ServiceDiscovery 서비스" },
    { L"SignerSigningJob", L"SignerSigningJob" },
    { L"SimpleDBDomain", L"SimpleDB 도메인" },
    { L"StorageGatewayFileShare", L"StorageGatewayFileShare" },
    { L"StorageGatewayGateway", L"StorageGateway 게이트웨이" },
    { L"StorageGatewayTape", L"StorageGatewayTape" },
    { L"StorageGatewayVolume", L"StorageGateway 볼륨" },
    { L"TransferServer", L"TransferServer" },
    { L"TransferServerUser", L"TransferServer 사용자" },
    { L"WAFRegionalByteMatchSet", L"WAFRegionalByteMatchSet" },
    { L"WAFRegionalByteMatchSetIP", L"WAFRegionalByteMatchSetIP" },
    { L"WAFRegionalIPSet", L"WAFRegionalIPSet" },
    { L"WAFRegionalIPSetIP", L"WAFRegionalIPSetIP" },
    { L"WAFRegionalRateBasedRule", L"WAFRegionalRateBasedRule" },
    { L"WAFRegionalRateBasedRulePredicate", L"WAFRegionalRateBasedRulePredicate" },
    { L"WAFRegionalRegexMatchSet", L"WAFRegionalRegexMatchSet" },
    { L"WAFRegionalRegexMatchTuple", L"WAFRegionalRegexMatchTuple" },
    { L"WAFRegionalRegexPatternSet", L"WAFRegionalRegexPatternSet" },
    { L"WAFRegionalRegexPatternString", L"WAFRegionalRegexPatternString" },
    { L"WAFRegionalRule", L"WAFRegionalRule" },
    { L"WAFRegionalRuleGroup", L"WAFRegionalRule 그룹" },
    { L"WAFRegionalRulePredicate", L"WAFRegionalRulePredicate" },
    { L"WAFRegionalWebACL", L"WAFRegionalWebACL" },
    { L"WAFRegionalWebACLRuleAttachment", L"WAFRegionalWebACLRuleAttachment" },
    { L"WAFRule", L"WAFRule" },
    { L"WAFWebACL", L"WAFWebACL" },
    { L"WAFWebACLRuleAttachment", L"WAFWebACLRuleAttachment" },
    { L"WAFv2IPSet", L"WAFv2IPSet" },
    { L"WAFv2RegexPatternSet", L"WAFv2RegexPatternSet" },
    { L"WAFv2RuleGroup", L"WAFv2Rule 그룹" },
    { L"WAFv2WebACL", L"WAFv2WebACL" },
    { L"WorkSpacesWorkspace", L"WorkSpacesWorkspace" },
    { L"XRayGroup", L"XRay 그룹" },
    { L"XRaySamplingRule", L"XRaySamplingRule" },
};
const int g_numResourceTypes = sizeof(g_resourceInfos) / sizeof(g_resourceInfos[0]);

#endif
